# Generated by Django 4.0.3 on 2024-01-23 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0002_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_mcode',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
