# Generated by Django 4.0.3 on 2024-01-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='serial_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
